forbidden_words = [
    # Original words
    "seamless",
    "em dashes",
    "—",
    "dive",
    "endless",
    "absurdly",
    "cranking",
    "down to the minute",
    "hidden strength",
    "precise",
    "handle",
    "struggle",
    "unpacks",
    "full breadth",
    "detailed",
    "demands",
    "deliver",
    "cover",
    "full range",
    "reveal",
    "what no one's talking about",
    "what really works",
    "goldmine",
    "cutting-edge",
    "innovative",
    "powerful",
    "game-changing",
    "unprecedented",
    "intuitive",
    "lightning-fast",
    "effortless",
    "state-of-the-art",
    "next-level",
    "robust",
    "versatile",
    "scalable",
    "groundbreaking",
    "streamlined",
    "optimized",
    "sophisticated",
    "transformative",
    "comprehensive",
    "seamlessly integrated",
    "dive deeper",
    "explore",
    "unlock",
    "discover",
    "unpack",
    "break down",
    "decode",
    "delve into",
    "analyze",
    "examine",
    "showcase",
    "showcasing",
    "unveil",
    "craft",
    "leverage",
    "empower",
    "navigate",
    "master",
    "build from scratch",
    "at its core",
    "behind the scenes",
    "step-by-step",
    "here's how it works",
    "let's break it down",
    "the beauty of",
    "the power of",
    "in the wild",
    "in the real world",
    "from the ground up",
    "under the hood",
    "makes it easier than ever",
    "you'll be surprised by",
    "what sets it apart",
    "the magic happens when",
    "bridges the gap",
    "boost",
    "maximize",
    "accelerate",
    "supercharge",
    "transform",
    "redefine",
    "streamline",
    "enhance",
    "revolutionize",
    "scale",
    "automate",
    "achieve more",
    "take it to the next level",
    "save countless hours",
    "cut through the noise",
    "in seconds",
    "like never before",
    "from start to finish",
    "effortlessly",
    "with ease",
    "smartly",
    "instantly",
    "on autopilot",
    "no manual work required",
    "powered by",
    "driven by data",
    "built with precision",
    "tailored to your needs",
    "hidden layers",
    "underlying",
    "uncovers",
    "depth",
    "Whether",
    "must-see",
    "must-",
    "stay in the loop",
    "essential",
    "capable",
    "this is a",
    "Introducing",
    "uncover",
    "Ready to",
    "scattered",
    "just clear",
    "fluff",
    "took control",
    "extra steps",
    "prioritized",
    "stepped in",
    "baller",
    # Corporate jargon
    "synergy",
    "paradigm",
    "ecosystem",
    "holistic",
    "proactive",
    "paradigm shift",
    "best practices",
    "actionable insights",
    "thought leader",
    "thought leadership",
    "circle back",
    "touch base",
    "low-hanging fruit",
    "quick win",
    "pain point",
    "value-add",
    "mission-critical",
    "bleeding edge",
    "vertical",
    "horizontal",
    "space",
    "deliverable",
    "stakeholder",
    "bandwidth",
    "ping",
    "align",
    "alignment",
    "deep dive",
    "30,000 foot view",
    "boil the ocean",
    "let's take this offline",
    "action item",
    "core competency",
    "moving forward",
    "at the end of the day",
    "win-win",
    "push the envelope",
    # AI-written phrases
    "in conclusion",
    "it's worth noting",
    "it's important to remember",
    "keep in mind",
    "don't forget",
    "make sure",
    "always remember",
    "it's crucial",
    "it's vital",
    "it's essential",
    "it's imperative",
    "moreover",
    "furthermore",
    "additionally",
    "in addition",
    "on the other hand",
    "however",
    "nevertheless",
    "nonetheless",
    "therefore",
    "thus",
    "hence",
    "consequently",
    "as a result",
    "due to",
    "owing to",
    "in light of",
    "given that",
    "considering that",
    "with that in mind",
    "that being said",
    "having said that",
    "all things considered",
    "at the end of the day",
    "when all is said and done",
    "ultimately",
    "in the final analysis",
    "to sum up",
    "to summarize",
    "in summary",
    "in closing",
    "finally",
    "lastly",
    "above all",
    "most importantly",
    "it cannot be overstated",
    "it should be emphasized",
    "it should be noted",
    "it bears repeating",
    "it's worth mentioning",
    "it's worth emphasizing",
    # Overly formal/academic
    "heretofore",
    "herewith",
    "henceforth",
    "wherewithal",
    "thence",
    "thusly",
    "whence",
    "whereas",
    "wherein",
    "whereby",
    "hereafter",
    "thereafter",
    "aforementioned",
    "aforethought",
    "heretofore",
    "notwithstanding",
    "albeit",
    "alas",
    "ergo",
    "ipso facto",
    "de facto",
    "status quo",
    "modus operandi",
    "quid pro quo",
    "raison d'être",
    "tour de force",
    "piece de resistance",
    "en masse",
    "vox populi",
    "ad nauseam",
    "ad infinitum",
    "per se",
    "vice versa",
    "et cetera",
    "et al",
    "ibid",
    "op cit",
    "loc cit",
    "viz",
    "ie",
    "eg",
    "cf",
    "qv",
    "sic",
    "stet",
    "nd",
    "vs",
    # Marketing hype
    "disruptive",
    "disruption",
    "future-proof",
    "game changer",
    "change the game",
    "revolutionary",
    "breakthrough",
    "pioneering",
    "visionary",
    "trailblazing",
    "epic",
    "mind-blowing",
    "jaw-dropping",
    "insane",
    "crazy",
    "unreal",
    "unbelievable",
    "incredible",
    "amazing",
    "awesome",
    "fantastic",
    "wonderful",
    "spectacular",
    "magnificent",
    "marvelous",
    "superb",
    "outstanding",
    "exceptional",
    "extraordinary",
    "remarkable",
    "phenomenal",
    "stunning",
    "breathtaking",
    "awe-inspiring",
    # Filler phrases
    "basically",
    "actually",
    "literally",
    "honestly",
    "truthfully",
    "frankly",
    "candidly",
    "genuinely",
    "sincerely",
    "truly",
    "really",
    "very",
    "quite",
    "rather",
    "somewhat",
    "somehow",
    "some way",
    "in some way",
    "in any way",
    "in any case",
    "in either case",
    "in that case",
    "in this case",
    "in many cases",
    "in most cases",
    "in all cases",
    "in every case",
    "in no case",
    "in some cases",
    "in certain cases",
    "in particular cases",
    "in special cases",
    "in rare cases",
    "in unusual cases",
    "in extreme cases",
    "in normal cases",
    "in typical cases",
    "in standard cases",
    "in general cases",
    "in specific cases",
    "in concrete cases",
    "in abstract cases",
    "in theoretical cases",
    "in practical cases",
    "in real cases",
    "in hypothetical cases",
    "in possible cases",
    "in impossible cases",
    "in likely cases",
    "in unlikely cases",
    "in probable cases",
    "in improbable cases",
]
